version: "3"
services:
  movie:
    build:
      context: ./service/movie/.
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev


