version: "3.2"
services:
  auth:
    build:
      context: ./service/auth/.
    ports:
      - published: 3000
        target: 3000
#    env_file: ./service/auth/.env
    environment:
      JWT_SECRET: secret

  movie:
    build:
     context: ./service/movie/.
    ports:
      - published: 8080
        target: 8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
