version: "3"
services:
  movies:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  #    env_file:
  #      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:


