name: Node.js CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        work-dir: [ service/movie ]
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Start Docker for Mongodb
        run: docker run -d -p 27017:27017 mongo

      - name: Install npm packages
        run: npm install
        working-directory: ${{ matrix.work-dir }}

      - name: Run `npm test`
        run: npm test
        working-directory: ${{ matrix.work-dir }}
        env:
          CI: true
          MONGODB_URI: mongodb://root:example@localhost:27017
